version: '3.8'

#command docker exec -it seating-db-container psql -U test -d seating-db
services:
  db:
    image: postgres:15
    container_name: seating-db-container
    environment:
      - POSTGRES_DB=seating-db
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - "5432:5432"
    volumes:
      - ./src/interfaces/data_access/init-db:/docker-entrypoint-initdb.d
  api:
    build: ./src/interfaces/api
    container_name: api-server
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
  #   build: .
  #   container_name: backend-container
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./src:/src
  #   environment:
  #     - DATABASE_URL=postgresql://test:test@db:5432/seating-db
  #   depends_on:
  #     - db
# volumes:
#   db-data: